// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyCnrsMRciVfw_Wz3rbguaWeQLHau1GxE',
    appId: '1:748835873318:web:db5235241ef582f9ab3ce7',
    messagingSenderId: '748835873318',
    projectId: 'pkr-staff-salary-management',
    authDomain: 'pkr-staff-salary-management.firebaseapp.com',
    storageBucket: 'pkr-staff-salary-management.firebasestorage.app',
    measurementId: 'G-WYN8467E1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3AZQy6RKorU2BpV-bqSaDIyYT86-GlxM',
    appId: '1:748835873318:android:48888a5b146017f0ab3ce7',
    messagingSenderId: '748835873318',
    projectId: 'pkr-staff-salary-management',
    storageBucket: 'pkr-staff-salary-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9kFyfTBDJ_RNppkzT8IGxTusFwbASpRA',
    appId: '1:748835873318:ios:d741506491e2acdeab3ce7',
    messagingSenderId: '748835873318',
    projectId: 'pkr-staff-salary-management',
    storageBucket: 'pkr-staff-salary-management.firebasestorage.app',
    iosBundleId: 'com.example.staffSalaryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9kFyfTBDJ_RNppkzT8IGxTusFwbASpRA',
    appId: '1:748835873318:ios:d741506491e2acdeab3ce7',
    messagingSenderId: '748835873318',
    projectId: 'pkr-staff-salary-management',
    storageBucket: 'pkr-staff-salary-management.firebasestorage.app',
    iosBundleId: 'com.example.staffSalaryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyCnrsMRciVfw_Wz3rbguaWeQLHau1GxE',
    appId: '1:748835873318:web:5608f27f724858beab3ce7',
    messagingSenderId: '748835873318',
    projectId: 'pkr-staff-salary-management',
    authDomain: 'pkr-staff-salary-management.firebaseapp.com',
    storageBucket: 'pkr-staff-salary-management.firebasestorage.app',
    measurementId: 'G-9SRKWBFC2V',
  );
}
