const List<String> kDepartments = [
  'Tamil',
  'English',
  'Computer Science',
  'Physics',
  'Mathematics',
  'Commerce',
  'Management',
  'Physical Director',
  'librarian',
  'Placement',
  'Non-Teaching',
  'Data Center',
  'IT-Hub',
  'Lab Assistant',
];